/* jshint node: true */ 
 var TAFFY = require('taffy'); 
 var books = TAFFY( 
[{"title":"Złota księga bajek","author":"Opracowanie zbiorowe","genre":"bajki"},
{"title":"Kopciuszek","author":"Januszewska Hanna","genre":"bajki"},
{"title":"Cuda Polski. Zamki i pałace","author":"Opracowanie zbiorowe","genre":"albumy"},
{"title":"Język C++. Kompendium wiedzy","author":"Stroustrup Bjarne","genre":"informatyka"},
{"title":"Node.js, MongoDB, AngularJS. Kompendium wiedzy","author":"Dayley Brad","genre":"informatyka"},
{"title":"Elementy grafiki komputerowej","author":"Michał Jankowski","genre":"informatyka"},
{"title":"AngularJS. Profesjonalne techniki","author":"Freeman Adam","genre":"informatyka"},
{"title":"Laravel. Tworzenie aplikacji. Receptury","author":"Matula Terry","genre":"informatyka"},
{"title":"HaemelOpenGL SuperBible: Comprehensive Tutorial and Reference (6th Edition) ","author":"Graham Sellers, Richard S. Wright, Jr., Nicholas Haemel","genre":"informatyka"},
{"title":"Prawo podatkowe. Przepisy 2015","author":"Prus Anna","genre":"prawo"},
{"title":"Zbiór cywilny 2015","author":"Opracowanie zbiorowe","genre":"prawo"},
{"title":"Zbiór karny 2015","author":"Opracowanie zbiorowe","genre":"prawo"},
{"title":"Potęga podświadomości","author":"Murphy Joseph","genre":"psychologia"},
{"title":"Test Marshmallow","author":"Mischel Walter","genre":"psychologia"},
{"title":"Kobiety, które kochają za bardzo","author":"Norwood Robin","genre":"psychologia"},
{"title":"Warszawa lata 60","author":"Opracowanie zbiorowe","genre":"sztuka"},
{"title":"Odczuwanie architektury","author":"Rassmusen Steen Eiler","genre":"sztuka"},
{"title":"Najpiękniejsze mosty świata","author":"Irteński Tadeusz","genre":"albumy"},
{"title":"Kroniki Diuny","author":"Herbert Frank","genre":"powieść"},
{"title":"Mesjasz Diuny","author":"Herbert Frank","genre":"powieść"},
{"title":"Dzieci Diuny","author":"Herbert Frank","genre":"powieść"},
{"title":"Sezon Burz","author":"Andrzej Sapkowski","genre":"fantastyka"},
{"title":"Ostatnie Życzenie","author":"Andrzej Sapkowski","genre":"fantastyka"},
{"title":"Krew Elfów","author":"Andrzej Sapkowski","genre":"fantastyka"},
{"title":"Dobić dziada","author":"Andrzej Pilipiuk","genre":"komiks"},
{"title":"Zabójca","author":"Andrzej Pilipiuk","genre":"komiks"},
{"title":"Krasnoludy","author":"Andrzej Pilipiuk","genre":"komiks"},
{"title":"Samochody moje","author":"Jeremy Clarkson","genre":"bajki"}]); 
 module.exports = books;